version: 0.1

environment_variables:
  plaintext:
    SLS_DEBUG: "*"

phases:
  install:
    commands:
      - sudo apt-get update -y
  pre_build:
    commands:
      - sudo npm install
  build:
    commands:
      - echo Build started on `date`
      - sudo npm start build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying build
      - aws s3 sync build/ s3://notes.jonkyops.com

artifacts:
  files:
    -  build
  discard-paths: yes
